import React,{useEffect,useMemo,useState} from 'react'
import{createRoot}from'react-dom/client'
import{ArrowLeft,BarChart3,BookOpen,CheckCircle2,ChevronRight,Download,Home,LogOut,Plus,RefreshCw,Search,Settings,WalletCards,X}from'lucide-react'
import{supabase}from'./supabase'
import'./style.css'
import'./settings.css'

const money=(n,c='HKD')=>new Intl.NumberFormat('zh-HK',{style:'currency',currency:c,minimumFractionDigits:Number(n||0)%1?2:0,maximumFractionDigits:2}).format(Number(n||0))
const weddingCats=['場地及餐飲','攝影及錄影','婚紗及服裝','化妝造型','場地佈置','娛樂及活動','婚戒及首飾','行政及法律','印刷及禮品','酒店及住宿','交通','其他']
const csvCell=value=>`"${String(value??'').replaceAll('"','""')}"`
function exportExpenses(project,expenses){
 const headings=['日期','分類','項目','總金額','已付','尚欠','付款狀態','負責人','備註']
 const rows=expenses.map(e=>[e.expense_date,e.categories?.name||'其他',e.title,Number(e.total_amount),Number(e.paid_amount),Number(e.outstanding_amount),e.payment_status==='paid'?'已付清':e.payment_status==='partial'?'部分付款':'未付款',e.responsible_person||'',e.notes||''])
 const csv='\ufeff'+[headings,...rows].map(row=>row.map(csvCell).join(',')).join('\r\n')
 const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a')
 a.href=url;a.download=`${project.name.replace(/[\\/:*?"<>|]/g,'-')}-帳目.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)
}
function App(){
 const[session,setSession]=useState(null),[projects,setProjects]=useState([]),[project,setProject]=useState(null),[expenses,setExpenses]=useState([]),[cats,setCats]=useState([]),[view,setView]=useState('home'),[sheet,setSheet]=useState(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState([])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(session)loadProjects()},[session])
 useEffect(()=>{if(project){setFilter('all');setQuery('');setSelected([]);loadProject()}},[project?.id])
 useEffect(()=>{if(!project)return;const ch=supabase.channel(`finance:${project.id}`).on('postgres_changes',{event:'*',schema:'public',filter:`project_id=eq.${project.id}`},loadProject).subscribe();return()=>supabase.removeChannel(ch)},[project?.id])
 async function loadProjects(){setLoading(true);const[{data:ps,error},{data:rows}]=await Promise.all([supabase.from('projects').select('*').is('archived_at',null).order('updated_at',{ascending:false}),supabase.from('expense_financials').select('project_id,total_amount,paid_amount,outstanding_amount')]);if(!error)setProjects((ps||[]).map(p=>({...p,expense_financials:(rows||[]).filter(r=>r.project_id===p.id)})));setLoading(false)}
 async function loadProject(){const[{data:raw},{data:c},{data:p}]=await Promise.all([supabase.from('expenses').select('*,categories(name),payments(amount)').eq('project_id',project.id).is('deleted_at',null).order('created_at',{ascending:false}),supabase.from('categories').select('*').eq('project_id',project.id).eq('kind','expense').order('sort_order'),supabase.from('projects').select('*').eq('id',project.id).single()]);const e=(raw||[]).map(x=>{const paid=(x.payments||[]).reduce((s,v)=>s+Number(v.amount),0),due=Math.max(Number(x.total_amount)-paid,0);return{...x,paid_amount:paid,outstanding_amount:due,payment_status:paid<=0?'unpaid':paid>=Number(x.total_amount)?'paid':'partial'}});setExpenses(e);setCats(c||[]);if(p){setProject(p);setProjects(x=>x.map(a=>a.id===p.id?p:a))}}
 const totals=useMemo(()=>expenses.reduce((a,e)=>({total:a.total+Number(e.total_amount),paid:a.paid+Number(e.paid_amount),due:a.due+Number(e.outstanding_amount)}),{total:0,paid:0,due:0}),[expenses])
 const shown=expenses.filter(e=>(!query||e.title.toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||(filter==='paid'?e.payment_status==='paid':e.payment_status!=='paid')))
 if(loading)return <main className="center"><div className="spinner"/></main>
 if(!session)return <Auth/>
 if(!project)return <Global projects={projects} reload={loadProjects} open={p=>{setProject(p);setView('overview')}} add={()=>setSheet('project')} sheet={sheet} close={()=>setSheet(null)} view={view} setView={setView} session={session}/>
 return <main><header><button className="icon" onClick={()=>{setProject(null);setView('home');loadProjects()}}><ArrowLeft/></button><Logo p={project}/><div><small>{project.project_type==='wedding'?'Wedding':'Project'}</small><b>{project.name}</b></div><button className="icon right" onClick={()=>{loadProject();loadProjects()}}><RefreshCw/></button></header>
  <section className="page">
   {view==='overview'&&<Dashboard t={totals} p={project} expenses={expenses}/>} 
   {view==='ledger'&&<Ledger list={shown} q={query} setQ={setQuery} filter={filter} setFilter={setFilter} selected={selected} setSelected={setSelected} currency={project.currency} open={e=>setSheet(e)} />}
   {view==='analytics'&&<Analytics list={expenses} currency={project.currency} open={name=>{setQuery('');setFilter('all');setView('ledger');setSheet({categoryDrill:name})}}/>}
   {view==='settings'&&<ProjectSettings p={project} expenses={expenses} email={session.user.email} save={async patch=>{const{error}=await supabase.from('projects').update(patch).eq('id',project.id);if(error)throw error;await loadProject();await loadProjects()}}/>}
  </section>
  <nav>{[['overview',Home,'總覽'],['ledger',BookOpen,'帳目'],['add',Plus,''],['analytics',BarChart3,'分析'],['settings',Settings,'設定']].map(([v,I,l])=><button key={v} className={view===v?'active':''} onClick={()=>v==='add'?setSheet('add'):setView(v)}><span className={v==='add'?'add':''}><I/></span>{l}</button>)}</nav>
  {sheet&&<Sheet close={()=>setSheet(null)}><SheetContent type={sheet} p={project} cats={cats} reload={loadProject} close={()=>setSheet(null)} expenses={expenses}/></Sheet>}
 </main>
}
function Auth(){const[email,setEmail]=useState('kingkwok2001@gmail.com'),[password,setPassword]=useState(''),[msg,setMsg]=useState('');async function go(signup=false){setMsg('處理中…');const r=signup?await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword({email,password});setMsg(r.error?r.error.message:(signup?'請檢查電郵完成驗證':'登入成功'))}return <main className="auth"><div className="brand"><div className="mark">PF</div><h1>Project Finance</h1><p>清楚知道要俾幾多、俾咗幾多、仲欠幾多。</p></div><div className="card form"><label>電郵<input value={email} onChange={e=>setEmail(e.target.value)} inputMode="email"/></label><label>密碼<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" onClick={()=>go(false)}>登入</button><button className="ghost" onClick={()=>go(true)}>建立帳號</button><small>{msg}</small></div></main>}
function Global({projects,open,add,sheet,close,view,setView,session}){const settings=view==='globalSettings';return <main><header><div><small>PROJECT FINANCE</small><h2>{settings?'帳號設定':'我的帳本'}</h2></div><div className="avatar">{(session.user.email||'C')[0].toUpperCase()}</div></header><section className="page">{settings?<AccountSettings email={session.user.email}/>:<><div className="welcome"><span>所有帳本</span><button className="icon" onClick={add} aria-label="新增帳本"><Plus/></button></div><div className="project-grid">{projects.map(p=>{const rows=p.expense_financials||[],t=rows.reduce((a,e)=>({total:a.total+Number(e.total_amount),paid:a.paid+Number(e.paid_amount),due:a.due+Number(e.outstanding_amount)}),{total:0,paid:0,due:0});return <button className="project-card" onClick={()=>open(p)} key={p.id}><Logo p={p}/><div className="project-title"><b>{p.name}</b><small>{p.project_type} · {p.currency}</small></div><ChevronRight/><div className="big"><small>尚欠</small><strong>{money(t.due,p.currency)}</strong></div><div className="triple"><span>總額<b>{money(t.total,p.currency)}</b></span><span>已付<b>{money(t.paid,p.currency)}</b></span></div><progress value={t.paid} max={t.total||1}/></button>})}{!projects.length&&<div className="empty"><WalletCards/><h3>建立第一個帳本</h3><p>登入後資料會安全同步到所有裝置。</p><button className="primary" onClick={add}>新增帳本</button></div>}</div></>}</section><nav><button className={!settings?'active':''} onClick={()=>setView('home')}><Home/>首頁</button><button onClick={add}><span className="add"><Plus/></span></button><button className={settings?'active':''} onClick={()=>setView('globalSettings')}><Settings/>設定</button></nav>{sheet&&<Sheet close={close}><NewProject close={close}/></Sheet>}</main>}
function Logo({p}){return p.logo_url?<img className="logo" src={p.logo_url}/>:<div className="logo fallback">{p.project_type==='wedding'?'CG':'PF'}</div>}
function Dashboard({t,p,expenses}){let pc=t.total?Math.round(t.paid/t.total*100):0;return <><div className="hero"><small>尚欠金額</small><h1>{money(t.due,p.currency)}</h1><div className="progress"><i style={{width:`${Math.min(pc,100)}%`}}/></div><span>{pc}% 已完成</span></div><div className="stats"><div><small>總額</small><b>{money(t.total,p.currency)}</b></div><div><small>已付</small><b>{money(t.paid,p.currency)}</b></div></div><h3>最近帳目</h3><div className="card list">{expenses.slice(0,4).map(e=><ExpenseRow key={e.id} e={e} c={p.currency}/>)}</div></>}
function Ledger({list,q,setQ,filter,setFilter,selected,setSelected,currency,open}){const chosen=list.filter(e=>selected.includes(e.id)).reduce((a,e)=>({t:a.t+Number(e.total_amount),p:a.p+Number(e.paid_amount),d:a.d+Number(e.outstanding_amount)}),{t:0,p:0,d:0});return <><h2>帳目 <small>{list.length} 筆支出</small></h2><div className="search"><Search/><input placeholder="搜尋項目" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="chips">{[['all','全部'],['unpaid','未付清'],['paid','已付清']].map(x=><button className={filter===x[0]?'on':''} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div>{selected.length>0&&<div className="selection"><b>已選 {selected.length} 項</b><span>總額 {money(chosen.t,currency)} · 已付 {money(chosen.p,currency)} · 尚欠 {money(chosen.d,currency)}</span></div>}<div className="card list">{list.map(e=><div className="selectrow"><input type="checkbox" checked={selected.includes(e.id)} onChange={()=>setSelected(s=>s.includes(e.id)?s.filter(x=>x!==e.id):[...s,e.id])}/><button onClick={()=>open(e)}><ExpenseRow e={e} c={currency}/></button></div>)}{!list.length&&<div className="empty"><p>目前篩選下沒有帳目</p></div>}</div></>}
function ExpenseRow({e,c}){return <div className="expense"><div><b>{e.title}</b><small>{e.categories?.name||'其他'} · {e.payment_status==='paid'?'已付清':e.payment_status==='partial'?'部分付款':'未付款'}</small></div><div><b>{money(e.total_amount,c)}</b><small className="due">欠 {money(e.outstanding_amount,c)}</small></div></div>}
function Analytics({list,currency,open}){const groups=Object.values(list.reduce((a,e)=>{let n=e.categories?.name||'其他';a[n]??={name:n,total:0,paid:0,count:0};a[n].total+=Number(e.total_amount);a[n].paid+=Number(e.paid_amount);a[n].count++;return a},{})).sort((a,b)=>b.total-a.total);return <><h2>分析</h2><div className="card list">{groups.map(g=><button className="cat" onClick={()=>open(g.name)}><div><b>{g.name}</b><small>{g.count} 項</small></div><span><b>{money(g.total,currency)}</b><ChevronRight/></span></button>)}</div></>}
function AccountSettings({email}){const[busy,setBusy]=useState(false),[msg,setMsg]=useState('');async function logout(){setBusy(true);const{error}=await supabase.auth.signOut({scope:'local'});if(error){setMsg(`登出失敗：${error.message}`);setBusy(false)}}return <><div className="card settings-card"><small>登入帳號</small><b>{email}</b></div><div className="card form"><h3>帳號</h3><p className="muted">你的帳本會透過此帳號同步至其他裝置。</p>{msg&&<div className="notice error">{msg}</div>}<button className="danger action-with-icon" disabled={busy} onClick={logout}><LogOut/>{busy?'登出中…':'登出'}</button></div></>}
function ProjectSettings({p,save,expenses,email}){const[name,setName]=useState(p.name),[income,setIncome]=useState(p.income_enabled),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');async function submit(){setSaving(true);setMsg('');try{await save({name:name.trim()||p.name,income_enabled:income});setMsg('saved')}catch(error){setMsg(error.message||'儲存失敗')}finally{setSaving(false)}}return <><h2>帳本設定</h2><div className="card form"><label>帳本名稱<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="switch">啟用收入模組<input type="checkbox" checked={income} onChange={e=>setIncome(e.target.checked)}/></label><button className="primary" disabled={saving} onClick={submit}>{saving?'儲存中…':'儲存設定'}</button>{msg==='saved'&&<div className="notice success"><CheckCircle2/>已儲存設定</div>}{msg&&msg!=='saved'&&<div className="notice error">{msg}</div>}</div><h3 className="section-title">匯出資料</h3><div className="card form"><p className="muted">匯出目前帳本全部 {expenses.length} 筆支出。CSV 可直接用 Excel、Numbers 或 Google Sheets 開啟。</p><button className="ghost action-with-icon" onClick={()=>exportExpenses(p,expenses)}><Download/>匯出 CSV</button></div><h3 className="section-title">帳號</h3><div className="card settings-card"><small>登入帳號</small><b>{email}</b></div></>}
function Sheet({children,close}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="sheet"><button className="close" onClick={close}><X/></button>{children}</div></div>}
function SheetContent({type,p,cats,reload,close,expenses}){if(type==='add')return <AddExpense p={p} cats={cats} done={async()=>{await reload();close()}}/>;if(type.categoryDrill){let rows=expenses.filter(e=>(e.categories?.name||'其他')===type.categoryDrill);return <><h2>{type.categoryDrill}</h2><div className="list">{rows.map(e=><ExpenseRow e={e} c={p.currency}/>)}</div></>}return <ExpenseDetail e={type} p={p} reload={reload} close={close}/>}
function AddExpense({p,cats,done}){const[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[cat,setCat]=useState(cats[0]?.id||''),[paid,setPaid]=useState('');async function save(){if(!title||!amount)return;const{data:e,error}=await supabase.from('expenses').insert({project_id:p.id,title,total_amount:Number(amount),category_id:cat||null}).select().single();if(!error&&Number(paid)>0)await supabase.from('payments').insert({project_id:p.id,expense_id:e.id,amount:Number(paid)});if(!error)done()}return <><h2>新增支出</h2><div className="form"><label>項目<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：場地"/></label><label>金額<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="HK$0"/></label><label>分類<select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option value={c.id}>{c.name}</option>)}</select></label><label>已付款金額（選填）<input inputMode="decimal" value={paid} onChange={e=>setPaid(e.target.value)} placeholder="HK$0"/></label><button className="primary" onClick={save}>完成</button></div></>}
function ExpenseDetail({e,p,reload,close}){const[amount,setAmount]=useState('');async function pay(){if(!amount)return;await supabase.from('payments').insert({project_id:p.id,expense_id:e.id,amount:Number(amount)});await reload();close()}async function del(){await supabase.from('expenses').update({deleted_at:new Date().toISOString()}).eq('id',e.id);await reload();close()}return <><h2>{e.title}</h2><div className="detail"><div><small>總額</small><b>{money(e.total_amount,p.currency)}</b></div><div><small>已付</small><b>{money(e.paid_amount,p.currency)}</b></div><div className="accent"><small>尚欠</small><b>{money(e.outstanding_amount,p.currency)}</b></div></div><div className="form"><label>今次俾幾多錢<input inputMode="decimal" value={amount} onChange={x=>setAmount(x.target.value)}/></label><button className="primary" onClick={pay}>新增付款</button><button className="danger" onClick={del}>刪除帳目</button></div></>}
function NewProject({close}){const[name,setName]=useState(''),[type,setType]=useState('wedding');async function save(){const{data:{user}}=await supabase.auth.getUser();const{data:p,error}=await supabase.from('projects').insert({owner_id:user.id,name,project_type:type,currency:'HKD',income_enabled:['daily','shared'].includes(type)}).select().single();if(error)return;let names=type==='wedding'?weddingCats:['其他'];await supabase.from('categories').insert(names.map((n,i)=>({project_id:p.id,name:n,kind:'expense',sort_order:i})));location.reload()}return <><h2>新增帳本</h2><div className="form"><label>帳本名稱<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：C&G Wedding"/></label><label>類型<select value={type} onChange={e=>setType(e.target.value)}><option value="wedding">Wedding</option><option value="travel">Travel</option><option value="renovation">Renovation</option><option value="daily">Daily Expenses</option><option value="shared">Shared Expenses</option><option value="custom">Custom</option></select></label><button className="primary" onClick={save}>建立帳本</button></div></>}
createRoot(document.getElementById('root')).render(<App/>)
